import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <head>
          <meta charSet="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
          <meta name="description" content="" />
          <meta name="author" content="" />
          <title>Freelancer - Start Bootstrap Theme</title>
          <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
          <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossOrigin="anonymous"></script>
          <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
          <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
          <link href="css/styles.css" rel="stylesheet" />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="row mb-5">
            <div className="col">
              <nav className="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
                <div className="container">
                  <a className="navbar-brand" href="#page-top">Start Bootstrap</a>
                  <button className="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i className="fas fa-bars"></i>
                  </button>
                  <div className="collapse navbar-collapse" id="navbarResponsive">
                    <ul className="navbar-nav ms-auto">
                      <li className="nav-item mx-0 mx-lg-1"><Link className="nav-link py-3 px-0 px-lg-3 rounded" href="/portfolio">Portfolio</Link></li>
                      <li className="nav-item mx-0 mx-lg-1"><Link className="nav-link py-3 px-0 px-lg-3 rounded" href="/about">About</Link></li>
                      <li className="nav-item mx-0 mx-lg-1"><Link className="nav-link py-3 px-0 px-lg-3 rounded" href="/contact">Contact</Link></li>
                    </ul>
                  </div>
                </div>
              </nav>
            </div>
          </div>
          <div className="row">
            <div className="col">
              {children}
            </div>
          </div>
          <div className="row mt-2">
            <div className="col">
              <footer className="footer text-center">
                <div className="container">
                  <div className="row">

                    <div className="col-lg-4 mb-5 mb-lg-0">
                      <h4 className="text-uppercase mb-4">Location</h4>
                      <p className="lead mb-0">
                        2215 John Daniel Drive
                        <br />
                        Clark, MO 65243
                      </p>
                    </div>

                    <div className="col-lg-4 mb-5 mb-lg-0">
                      <h4 className="text-uppercase mb-4">Around the Web</h4>
                      <a className="btn btn-outline-light btn-social mx-1" href="#!"><i className="fab fa-fw fa-facebook-f"></i></a>
                      <a className="btn btn-outline-light btn-social mx-1" href="#!"><i className="fab fa-fw fa-twitter"></i></a>
                      <a className="btn btn-outline-light btn-social mx-1" href="#!"><i className="fab fa-fw fa-linkedin-in"></i></a>
                      <a className="btn btn-outline-light btn-social mx-1" href="#!"><i className="fab fa-fw fa-dribbble"></i></a>
                    </div>

                    <div className="col-lg-4">
                      <h4 className="text-uppercase mb-4">About Freelancer</h4>
                      <p className="lead mb-0">
                        Freelance is a free to use, MIT licensed Bootstrap theme created by
                        <a href="http://startbootstrap.com">Start Bootstrap</a>
                        .
                      </p>
                    </div>
                  </div>
                </div>
              </footer>
              <div className="copyright py-4 text-center text-white">
                <div className="container"><small>Copyright &copy; Your Website 2023</small></div>
              </div>
            </div>
          </div>
          <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        </body>
      </html>
    </>
  );
}
