import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossOrigin="anonymous" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="row">
          <div className="col">
            <ul className="nav">
              <li className="nav-item">
                <Link className="nav-link py-3 px-0 px-lg-3 rounded" href="/students">Students</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link py-3 px-0 px-lg-3 rounded" href="/faculties">Faculties</Link>
              </li>
            </ul>
          </div>
        </div>
        <div className="row m-1">
          <div className="col">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
